export const activityStubs = {
  basic: {
    activity: 'Write a note of appreciation to someone',
    type: 'social',
    participants: 1,
    price: 0,
    link: '',
    key: '1770521',
    accessibility: 0,
  },
  withLink: {
    activity: 'Learn Express.js',
    accessibility: 0.25,
    type: 'education',
    participants: 1,
    price: 0.1,
    link: 'https://expressjs.com/',
    key: '3943506',
  },
  pricePaid: {
    activity: 'Visit a nearby museum',
    availability: 0.7,
    type: 'recreational',
    participants: 1,
    price: 0.2,
    accessibility: 'Few to no challenges',
    link: '',
    key: '5490351',
  },
  with2people: {
    activity: 'Play a game of tennis with a friend',
    availability: 0.4,
    type: 'social',
    participants: 2,
    price: 0.1,
    accessibility: 'Major challenges',
    duration: 'minutes',
    kidFriendly: true,
    link: '',
    key: '1093640',
  },
}
